[[cells]]
name = "sudt-info-type-script"
enable_type_id = false
location = { file = "build/release/sudt-info-type-script" }

[[cells]]
name = "sudt-info-lock-script"
enable_type_id = false
location = { file = "build/release/sudt-info-lock-script" }

[[cells]]
name = "sudt-liquidity-lock-script"
enable_type_id = false
location = { file = "build/release/sudt-liquidity-lock-script"}

[[cells]]
name = "sudt-swap-lock-script"
enable_type_id = false
location = { file = "build/release/sudt-swap-lock-script"}

# Replace with your own lock if you want to unlock deployed cells.
# For example the secp256k1 lock
[lock]
code_hash = "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8"
args = "0x0000000000000000000000000000000000000000"
hash_type = "type"

